# Generated by Django 5.1.7 on 2025-05-11 17:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programa', '0008_remove_programaparticipante_activo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pre', 'Pre'), ('post', 'Post')], default='pre', max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(default='Sin descripción')),
                ('preguntas', models.JSONField(default=list)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuestionarios', to='programa.programa')),
            ],
            options={
                'unique_together': {('programa', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='RespuestaCuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuestas', models.JSONField(default=dict)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='cuestionario.cuestionario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_cuestionario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('cuestionario', 'usuario')},
            },
        ),
    ]
