# Generated by Django 5.1.7 on 2025-06-18 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuestionario', '0001_initial'),
        ('programa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuestionario',
            name='programa',
            field=models.ForeignKey(db_column='programa_id', on_delete=django.db.models.deletion.CASCADE, related_name='cuestionarios', to='programa.programa'),
        ),
        migrations.AddField(
            model_name='respuestacuestionario',
            name='cuestionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='cuestionario.cuestionario'),
        ),
    ]
