# Generated by Django 5.1.7 on 2025-05-11 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuestionario', '0001_initial'),
        ('programa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cuestionario',
            name='programa',
            field=models.ForeignKey(db_column='programa_id', on_delete=django.db.models.deletion.CASCADE, related_name='cuestionarios', to='programa.programa'),
        ),
        migrations.AddField(
            model_name='respuestacuestionario',
            name='cuestionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='cuestionario.cuestionario'),
        ),
        migrations.AddField(
            model_name='respuestacuestionario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_cuestionario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='cuestionario',
            unique_together={('programa', 'tipo')},
        ),
        migrations.AlterUniqueTogether(
            name='respuestacuestionario',
            unique_together={('cuestionario', 'usuario')},
        ),
    ]
