# Generated by Django 5.1.7 on 2025-06-18 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuestionario', '0002_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestacuestionario',
            name='participante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_cuestionario', to='usuario.participante'),
        ),
        migrations.AlterUniqueTogether(
            name='cuestionario',
            unique_together={('programa', 'momento')},
        ),
        migrations.AlterUniqueTogether(
            name='respuestacuestionario',
            unique_together={('cuestionario', 'participante')},
        ),
    ]
