# Generated by Django 5.1.7 on 2025-05-11 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0002_initial'),
    ]

    operations = [
    ]
