# Generated by Django 5.1.7 on 2025-06-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuestionario',
            name='tipo_cuestionario',
            field=models.CharField(choices=[('personalizado', 'Personalizado'), ('likert', 'Escala Likert'), ('predefinido', 'Predefinido')], default='personalizado', max_length=50),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='tipo',
            field=models.CharField(choices=[('pre', 'Pre'), ('post', 'Post')], default='pre', max_length=50),
        ),
    ]
