# Generated by Django 5.1.7 on 2025-06-09 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0004_cuestionario_tipo_cuestionario_and_more'),
        ('programa', '0006_remove_inscripcionprograma_cuestionarios_completados_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuestionario',
            old_name='tipo',
            new_name='momento',
        ),
        migrations.AlterUniqueTogether(
            name='cuestionario',
            unique_together={('programa', 'momento')},
        ),
    ]
