# Generated by Django 5.1.7 on 2025-06-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiarioSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.FloatField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sesion__semana', 'fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('semana', models.PositiveIntegerField(help_text='Número de semana en el programa')),
                ('duracion_estimada', models.PositiveIntegerField(blank=True, help_text='Duración estimada en minutos', null=True)),
                ('tipo_practica', models.CharField(choices=[('breath', 'Atención a la Respiración'), ('sounds', 'Atención a los Sonidos'), ('visual_object', 'Atención a un Objeto visual'), ('senses', 'Atención a los Sentidos'), ('open_awareness', 'Conciencia Abierta'), ('loving_kindness', 'Loving Kindness (Bondad Amorosa)'), ('body_scan', 'Escaneo Corporal'), ('self_compassion', 'Auto-compasión'), ('mindful_movement', 'Movimiento Consciente'), ('otro', 'Otro')], default='breath', max_length=50)),
                ('tipo_contenido', models.CharField(choices=[('temporizador', 'Temporizador'), ('enlace', 'Enlace'), ('audio', 'Audio'), ('video', 'Video')], default='temporizador', max_length=50)),
                ('tipo_escala', models.CharField(blank=True, choices=[('estado_emocional', '¿Cómo te sientes emocionalmente en este momento? [1–5]'), ('estres_actual', '¿Cuánto estrés sientes ahora mismo? [0–10]'), ('bienestar_general', '¿Cómo valoras tu bienestar general ahora mismo? [0–10]'), ('utilidad_sesion', '¿Cuánto te ha servido esta sesión de mindfulness? [1–5]'), ('claridad_mental', '¿Cuánta claridad mental sientes ahora mismo? [1–5]'), ('presencia', '¿Qué tan presente te sientes en este momento? [1–5]')], default='estado_emocional', max_length=50, null=True)),
                ('contenido_temporizador', models.PositiveIntegerField(blank=True, help_text='Duración del temporizador en minutos', null=True)),
                ('contenido_url', models.URLField(blank=True, help_text='URL para contenido externo o cargado', null=True)),
                ('contenido_audio', models.FileField(blank=True, help_text='Archivo de audio', null=True, upload_to='audio/')),
                ('contenido_video', models.FileField(blank=True, help_text='Archivo de video', null=True, upload_to='video/')),
                ('video_fondo', models.CharField(blank=True, help_text='Nombre del video de fondo para el temporizador', max_length=100, null=True)),
            ],
            options={
                'ordering': ['programa', 'semana'],
            },
        ),
    ]
