# Generated by Django 5.1.7 on 2025-05-11 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programa', '0001_initial'),
        ('usuario', '0007_remove_investigador_niveleducativo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('semana', models.PositiveIntegerField(help_text='Número de semana en el programa')),
                ('duracion_estimada', models.PositiveIntegerField(blank=True, help_text='Duración estimada en minutos', null=True)),
                ('tipo_practica', models.CharField(choices=[('focus_attention', 'Atención Focalizada'), ('open_monitoring', 'Monitoreo Abierto'), ('loving_kindness', 'Amorosa Bondad'), ('body_scan', 'Escaneo Corporal'), ('mindful_movement', 'Movimiento Consciente'), ('self_compassion', 'Auto-compasión'), ('otro', 'Otro')], default='focus_attention', max_length=50)),
                ('tipo_contenido', models.CharField(choices=[('temporizador', 'Temporizador'), ('enlace', 'Enlace'), ('audio', 'Audio'), ('video', 'Video')], default='temporizador', max_length=50)),
                ('tipo_escala', models.CharField(choices=[('emocional', 'Estado emocional [1–5]'), ('utilidad', 'Utilidad de la sesión [1–5]'), ('estres', 'PSS (estrés) [0–4]'), ('compromiso', 'UWES-3 (compromiso) [1–5]'), ('bienestar', 'VAS (bienestar general) [0–10]')], default='emocional', max_length=50)),
                ('contenido_temporizador', models.PositiveIntegerField(blank=True, help_text='Duración del temporizador en minutos', null=True)),
                ('contenido_url', models.URLField(blank=True, help_text='URL para contenido externo o cargado', null=True)),
                ('contenido_audio', models.FileField(blank=True, help_text='Archivo de audio', null=True, upload_to='audio/')),
                ('contenido_video', models.FileField(blank=True, help_text='Archivo de video', null=True, upload_to='video/')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='programa.programa')),
            ],
            options={
                'ordering': ['programa', 'semana'],
                'unique_together': {('programa', 'semana')},
            },
        ),
        migrations.CreateModel(
            name='DiarioSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.FloatField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diarios', to='usuario.participante')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diarios', to='sesion.sesion')),
            ],
            options={
                'ordering': ['sesion__semana', 'fecha_creacion'],
                'unique_together': {('participante', 'sesion')},
            },
        ),
    ]
