# Generated by Django 5.1.7 on 2025-05-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sesion',
            old_name='duracion_temporizador',
            new_name='contenido_temporizador',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='contenido_archivo',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='contenido_texto',
        ),
        migrations.AddField(
            model_name='sesion',
            name='contenido_audio',
            field=models.FileField(blank=True, help_text='Archivo de audio', null=True, upload_to='files/audio/'),
        ),
        migrations.AddField(
            model_name='sesion',
            name='contenido_video',
            field=models.FileField(blank=True, help_text='Archivo de video', null=True, upload_to='files/video/'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='tipo_contenido',
            field=models.CharField(choices=[('temporizador', 'Temporizador'), ('enlace', 'Enlace'), ('audio', 'Audio'), ('video', 'Video')], default='temporizador', max_length=50),
        ),
    ]
