# Generated by Django 5.1.7 on 2025-06-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='tipo_escala',
            field=models.CharField(blank=True, choices=[('emocional', 'Estado emocional [1–5]'), ('utilidad', 'Utilidad de la sesión [1–5]'), ('estres', 'PSS (estrés) [0–4]'), ('bienestar', 'VAS (bienestar general) [0–10]')], default='emocional', max_length=50, null=True),
        ),
    ]
