# Generated by Django 5.1.7 on 2025-05-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='tipo_practica',
            field=models.CharField(choices=[('breath', 'Atención a la Respiración'), ('sounds', 'Atención a los Sonidos'), ('visual_object', 'Atención Focalizada a Objeto visual'), ('senses', 'Atención Focalizada a Sentidos'), ('open_awareness', 'Conciencia Abierta'), ('loving_kindness', 'Loving Kindness (Bondad Amorosa)'), ('body_scan', 'Escaneo Corporal'), ('self_compassion', 'Auto-compasión'), ('mindful_movement', 'Movimiento Consciente'), ('otro', 'Otro')], default='breath', max_length=50),
        ),
    ]
