# Generated by Django 5.1.7 on 2025-05-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0002_rename_duracion_temporizador_sesion_contenido_temporizador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='contenido_audio',
            field=models.FileField(blank=True, help_text='Archivo de audio', null=True, upload_to='media/audio/'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='contenido_video',
            field=models.FileField(blank=True, help_text='Archivo de video', null=True, upload_to='media/video/'),
        ),
    ]
