# Generated by Django 5.1.7 on 2025-06-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0003_alter_sesion_tipo_practica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='tipo_practica',
            field=models.CharField(choices=[('breath', 'Atención a la Respiración'), ('sounds', 'Atención a los Sonidos'), ('visual_object', 'Atención a un Objeto visual'), ('senses', 'Atención a los Sentidos'), ('open_awareness', 'Conciencia Abierta'), ('loving_kindness', 'Loving Kindness (Bondad Amorosa)'), ('body_scan', 'Escaneo Corporal'), ('self_compassion', 'Auto-compasión'), ('mindful_movement', 'Movimiento Consciente'), ('otro', 'Otro')], default='breath', max_length=50),
        ),
    ]
