# Generated by Django 5.1.7 on 2025-06-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0003_alter_sesion_tipo_escala'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='video_fondo',
            field=models.CharField(blank=True, help_text='Nombre del video de fondo para el temporizador', max_length=100, null=True),
        ),
    ]
