# Generated by Django 5.1.7 on 2025-06-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0004_sesion_video_fondo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='tipo_escala',
            field=models.CharField(blank=True, choices=[('estado_emocional', '¿Cómo te sientes emocionalmente en este momento? [1–5]'), ('estres_actual', '¿Cuánto estrés sientes ahora mismo? [0–10]'), ('bienestar_general', '¿Cómo valoras tu bienestar general ahora mismo? [0–10]'), ('utilidad_sesion', '¿Cuánto te ha servido esta sesión de mindfulness? [1–5]'), ('claridad_mental', '¿Qué tanta claridad mental sientes ahora mismo? [1–5]'), ('presencia', '¿Qué tan presente te sientes en este momento? [1–5]')], default='estado_emocional', max_length=50, null=True),
        ),
    ]
