# Generated by Django 5.1.7 on 2025-05-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0004_alter_sesion_contenido_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='tipo_escala_diario',
            field=models.CharField(choices=[('emocional', 'Estado emocional [1–5]'), ('utilidad', 'Utilidad de la sesión [1–5]'), ('estres', 'PSS (estrés) [0–4]'), ('compromiso', 'UWES-3 (compromiso) [1–5]'), ('bienestar', 'VAS (bienestar general) [0–10]')], default='emocional', max_length=50),
        ),
    ]
