# Generated by Django 5.1.7 on 2025-05-10 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0005_sesion_tipo_escala_diario'),
        ('usuario', '0007_remove_investigador_niveleducativo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesion',
            name='tipo_escala_diario',
        ),
        migrations.CreateModel(
            name='DiarioSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_escala', models.CharField(choices=[('emocional', 'Estado emocional [1–5]'), ('utilidad', 'Utilidad de la sesión [1–5]'), ('estres', 'PSS (estrés) [0–4]'), ('compromiso', 'UWES-3 (compromiso) [1–5]'), ('bienestar', 'VAS (bienestar general) [0–10]')], max_length=50)),
                ('valoracion', models.FloatField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diarios', to='usuario.participante')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diarios', to='sesion.sesion')),
            ],
            options={
                'ordering': ['sesion__semana', 'fecha_creacion'],
                'unique_together': {('participante', 'sesion', 'tipo_escala')},
            },
        ),
        migrations.DeleteModel(
            name='DiarioRespuesta',
        ),
    ]
