# Generated by Django 5.1.7 on 2025-05-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0006_remove_sesion_tipo_escala_diario_diariosesion_and_more'),
        ('usuario', '0007_remove_investigador_niveleducativo_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='diariosesion',
            unique_together={('participante', 'sesion')},
        ),
        migrations.AddField(
            model_name='sesion',
            name='tipo_escala',
            field=models.CharField(choices=[('emocional', 'Estado emocional [1–5]'), ('utilidad', 'Utilidad de la sesión [1–5]'), ('estres', 'PSS (estrés) [0–4]'), ('compromiso', 'UWES-3 (compromiso) [1–5]'), ('bienestar', 'VAS (bienestar general) [0–10]')], default='emocional', max_length=50),
        ),
        migrations.RemoveField(
            model_name='diariosesion',
            name='tipo_escala',
        ),
    ]
