# Generated by Django 5.1.7 on 2025-04-24 18:49

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('INVESTIGADOR', 'Investigador'), ('PARTICIPANTE', 'Participante')], default='PARTICIPANTE', max_length=20)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro'), ('prefiero_no_decir', 'Prefiero no decir')], default='prefiero_no_decir', max_length=20)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Investigador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('ocupacion', models.CharField(blank=True, max_length=100)),
                ('nivel_educativo', models.CharField(blank=True, choices=[('sin_estudios', 'Sin Estudios'), ('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('bachillerato', 'Bachillerato'), ('formacion_profesional', 'Formación Profesional'), ('universidad', 'Universidad'), ('master', 'Master'), ('doctorado', 'Doctorado'), ('otros', 'Otros')], default='universidad', max_length=50)),
                ('areas_interes', models.JSONField(blank=True, default=list)),
                ('experiencia_investigacion', models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No'), ('En parte', 'En parte')], default='No', max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_investigador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupacion', models.CharField(blank=True, max_length=100)),
                ('nivel_educativo', models.CharField(blank=True, choices=[('sin_estudios', 'Sin Estudios'), ('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('bachillerato', 'Bachillerato'), ('formacion_profesional', 'Formación Profesional'), ('universidad', 'Universidad'), ('master', 'Master'), ('doctorado', 'Doctorado'), ('otros', 'Otros')], default='universidad', max_length=50)),
                ('experiencia_mindfulness', models.CharField(blank=True, choices=[('ninguna', 'Ninguna'), ('menos de 6 meses', 'Menos de 6 meses'), ('6 meses - 1 año', '6 meses - 1 año'), ('1 - 2 años', '1 - 2 años'), ('más de 2 años', 'Más de 2 años')], default='ninguna', max_length=20)),
                ('condiciones_salud', models.TextField(blank=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_participante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
