# Generated by Django 5.1.7 on 2025-06-06 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0006_remove_inscripcionprograma_cuestionarios_completados_and_more'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDAnonimoParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_anonimo', models.CharField(max_length=9, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ids_anonimos', to='usuario.participante')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ids_anonimos_participantes', to='programa.programa')),
            ],
            options={
                'db_table': 'usuario_idanonimoparticipante',
                'unique_together': {('participante', 'programa')},
            },
        ),
    ]
