# Generated by Django 5.1.7 on 2025-06-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='experienciaMindfulness',
            field=models.CharField(blank=True, choices=[('ninguna', 'Ninguna'), ('menos_de_6_meses', 'Menos de 6 meses'), ('6_meses_1_ano', '6 meses - 1 año'), ('1_2_anos', '1 - 2 años'), ('2_10_anos', '2 - 10 años'), ('mas_de_10_anos', 'Más de 10 años')], default='ninguna', max_length=20),
        ),
    ]
