# Generated by Django 5.1.7 on 2025-06-09 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_idanonimoparticipante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IDAnonimoParticipante',
        ),
    ]
