# Generated by Django 5.1.7 on 2025-06-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_participante_experienciamindfulness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='experienciaMindfulness',
            field=models.CharField(blank=True, choices=[('ninguna', 'Ninguna'), ('menos_6_meses', 'Menos de 6 meses'), ('entre_6_12_meses', '6 meses - 1 año'), ('entre_1_2_anos', '1 - 2 años'), ('entre_2_10_anos', '2 - 10 años'), ('mas_10_anos', 'Más de 10 años')], default='ninguna', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nivelEducativo',
            field=models.CharField(blank=True, choices=[('sin_estudios', 'Sin Estudios'), ('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('bachillerato', 'Bachillerato'), ('fp', 'Formación Profesional'), ('universidad', 'Universidad'), ('master', 'Master'), ('doctorado', 'Doctorado'), ('otros', 'Otros')], default='universidad', max_length=50),
        ),
    ]
