# Generated by Django 5.1.7 on 2025-04-24 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investigador',
            old_name='areas_interes',
            new_name='areasInteres',
        ),
        migrations.RenameField(
            model_name='investigador',
            old_name='experiencia_investigacion',
            new_name='experienciaInvestigacion',
        ),
        migrations.RenameField(
            model_name='investigador',
            old_name='nivel_educativo',
            new_name='nivelEducativo',
        ),
        migrations.RenameField(
            model_name='participante',
            old_name='condiciones_salud',
            new_name='condicionesSalud',
        ),
        migrations.RenameField(
            model_name='participante',
            old_name='experiencia_mindfulness',
            new_name='experienciaMindfulness',
        ),
        migrations.RenameField(
            model_name='participante',
            old_name='nivel_educativo',
            new_name='nivelEducativo',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='fecha_nacimiento',
            new_name='fechaNacimiento',
        ),
    ]
