# Generated by Django 5.1.7 on 2025-06-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_delete_idanonimoparticipante'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='aceptaTerminos',
            field=models.BooleanField(default=False),
        ),
    ]
