# Generated by Django 5.1.7 on 2025-04-24 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_rename_areas_interes_investigador_areasinteres_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='last_name',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='first_name',
            new_name='nombre',
        ),
    ]
