# Generated by Django 5.1.7 on 2025-04-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_rename_last_name_usuario_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='experienciaMindfulness',
            field=models.CharField(blank=True, choices=[('ninguna', 'Ninguna'), ('menos_de_6_meses', 'Menos de 6 meses'), ('6_meses_1_ano', '6 meses - 1 año'), ('1_2_anos', '1 - 2 años'), ('mas_de_2_anos', 'Más de 2 años')], default='ninguna', max_length=20),
        ),
    ]
