# Generated by Django 5.1.7 on 2025-04-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_participante_telefono_participante_ubicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigador',
            name='nivelEducativo',
        ),
        migrations.RemoveField(
            model_name='investigador',
            name='ocupacion',
        ),
        migrations.RemoveField(
            model_name='investigador',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='investigador',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='nivelEducativo',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='ocupacion',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='usuario',
            name='nivelEducativo',
            field=models.CharField(blank=True, choices=[('sin_estudios', 'Sin Estudios'), ('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('bachillerato', 'Bachillerato'), ('formacion_profesional', 'Formación Profesional'), ('universidad', 'Universidad'), ('master', 'Master'), ('doctorado', 'Doctorado'), ('otros', 'Otros')], default='universidad', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
