# Generated by Django 5.1.7 on 2025-05-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InscripcionPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado_programa', models.CharField(choices=[('en progreso', 'En progreso'), ('completado', 'Completado')], default='en progreso', max_length=20)),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('tipo_contexto', models.CharField(choices=[('académico', 'Académico'), ('laboral', 'Laboral'), ('clínico/terapéutico', 'Clínico/Terapéutico'), ('deportivo', 'Deportivo'), ('personal/desarrollo individual', 'Personal/Desarrollo Individual'), ('otro', 'Otro')], default='personal/desarrollo individual', max_length=50)),
                ('enfoque_metodologico', models.CharField(choices=[('MBSR', 'MBSR (Mindfulness-Based Stress Reduction)'), ('MBCT', 'MBCT (Mindfulness-Based Cognitive Therapy)'), ('ACT', 'ACT (Acceptance and Commitment Therapy)'), ('DBT', 'DBT (Dialectical Behavior Therapy)'), ('MSC', 'MSC (Mindful Self-Compassion)'), ('MMT', 'MMT (Mindfulness Meditation Training)'), ('propio', 'Enfoque propio'), ('otro', 'Otro')], default='MBSR', max_length=50)),
                ('poblacion_objetivo', models.CharField(blank=True, max_length=255, null=True)),
                ('duracion_semanas', models.PositiveIntegerField()),
                ('estado_publicacion', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('finalizado', 'Finalizado')], default='borrador', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
