# Generated by Django 5.1.7 on 2025-05-03 19:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programa',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.RenameField(
            model_name='programa',
            old_name='duracion',
            new_name='duracion_semanas',
        ),
        migrations.RenameField(
            model_name='programa',
            old_name='titulo',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='estado',
        ),
        migrations.AddField(
            model_name='programa',
            name='cuestionario_post',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='programa',
            name='cuestionario_pre',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='programa',
            name='enfoque_metodologico',
            field=models.CharField(choices=[('MBSR', 'MBSR (Mindfulness-Based Stress Reduction)'), ('MBCT', 'MBCT (Mindfulness-Based Cognitive Therapy)'), ('ACT', 'ACT (Acceptance and Commitment Therapy)'), ('DBT', 'DBT (Dialectical Behavior Therapy)'), ('MSC', 'MSC (Mindful Self-Compassion)'), ('MMT', 'MMT (Mindfulness Meditation Training)'), ('propio', 'Enfoque propio'), ('otro', 'Otro')], default='MBSR', max_length=50),
        ),
        migrations.AddField(
            model_name='programa',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='programa',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programa',
            name='objetivos',
            field=models.TextField(default='Sin objetivos definidos'),
        ),
        migrations.AddField(
            model_name='programa',
            name='poblacion_objetivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='programa',
            name='tipo_contexto',
            field=models.CharField(choices=[('académico', 'Académico'), ('laboral', 'Laboral'), ('clínico/terapéutico', 'Clínico/Terapéutico'), ('deportivo', 'Deportivo'), ('personal/desarrollo individual', 'Personal/Desarrollo Individual'), ('otro', 'Otro')], default='personal/desarrollo individual', max_length=50),
        ),
    ]
