# Generated by Django 5.1.7 on 2025-06-06 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuestionario', '0003_initial'),
        ('programa', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionprograma',
            name='participante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='usuario.participante'),
        ),
        migrations.AddField(
            model_name='programa',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='usuario.investigador'),
        ),
        migrations.AddField(
            model_name='programa',
            name='cuestionario_post',
            field=models.ForeignKey(blank=True, db_column='cuestionario_post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas_post', to='cuestionario.cuestionario'),
        ),
        migrations.AddField(
            model_name='programa',
            name='cuestionario_pre',
            field=models.ForeignKey(blank=True, db_column='cuestionario_pre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas_pre', to='cuestionario.cuestionario'),
        ),
        migrations.AddField(
            model_name='programa',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='programas_inscritos', to='usuario.participante'),
        ),
        migrations.AddField(
            model_name='inscripcionprograma',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='programa.programa'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcionprograma',
            unique_together={('programa', 'participante')},
        ),
    ]
