# Generated by Django 5.1.7 on 2025-03-31 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programa', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='usuario.investigador'),
        ),
        migrations.AddField(
            model_name='programa',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='programas_inscritos', to='usuario.participante'),
        ),
    ]
