# Generated by Django 5.1.7 on 2025-05-13 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='programas_inscritos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='programaparticipante',
            name='participante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
