# Generated by Django 5.1.7 on 2025-06-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcionprograma',
            name='estado_programa',
            field=models.CharField(choices=[('en_progreso', 'En progreso'), ('completado', 'Completado')], default='en_progreso', max_length=20),
        ),
        migrations.AlterField(
            model_name='programa',
            name='tipo_contexto',
            field=models.CharField(choices=[('académico', 'Académico'), ('laboral', 'Laboral'), ('clínico', 'Clínico/Terapéutico'), ('deportivo', 'Deportivo'), ('crecimiento_personal', 'Crecimiento Personal'), ('otro', 'Otro')], default='crecimiento_personal', max_length=50),
        ),
    ]
