# Generated by Django 5.1.7 on 2025-06-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='tipo_evaluacion',
            field=models.CharField(choices=[('cuestionarios', 'Cuestionarios Pre/Post'), ('diarios', 'Diarios de Autoevaluación Post-Sesión'), ('ambos', 'Cuestionarios y Diarios')], default='ambos', max_length=20),
        ),
    ]
