# Generated by Django 5.1.7 on 2025-05-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0002_alter_programa_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='objetivos',
        ),
        migrations.AddField(
            model_name='programa',
            name='escala',
            field=models.CharField(choices=[('emocional', 'Estado emocional [1–5]'), ('utilidad', 'Utilidad de la sesión [1–5]'), ('estres', 'PSS (estrés) [0–4]'), ('compromiso', 'UWES-3 (compromiso) [1–5]'), ('bienestar', 'VAS (bienestar general) [0–10]')], default='emocional', max_length=50),
        ),
    ]
