# Generated by Django 5.1.7 on 2025-06-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0003_alter_programa_tipo_evaluacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='tipo_evaluacion',
        ),
        migrations.AddField(
            model_name='programa',
            name='tiene_cuestionarios',
            field=models.BooleanField(default=True, help_text='Indica si el programa usa cuestionarios pre/post'),
        ),
        migrations.AddField(
            model_name='programa',
            name='tiene_diarios',
            field=models.BooleanField(default=True, help_text='Indica si el programa usa diarios de autoevaluación post-sesión'),
        ),
    ]
