# Generated by Django 5.1.7 on 2025-06-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0003_alter_inscripcionprograma_estado_programa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='fecha_finalizacion',
        ),
        migrations.AlterField(
            model_name='programa',
            name='estado_publicacion',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], default='borrador', max_length=20),
        ),
    ]
