# Generated by Django 5.1.7 on 2025-05-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0003_remove_programa_objetivos_programa_escala'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='estado_publicacion',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], default='borrador', max_length=20),
        ),
        migrations.AddField(
            model_name='programa',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
