# Generated by Django 5.1.7 on 2025-06-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0004_remove_programa_tipo_evaluacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionprograma',
            name='cuestionarios_completados',
            field=models.BooleanField(default=False, help_text='Indica si se han completado los cuestionarios pre/post'),
        ),
        migrations.AddField(
            model_name='inscripcionprograma',
            name='diarios_completados',
            field=models.BooleanField(default=False, help_text='Indica si se han completado todos los diarios'),
        ),
        migrations.AddField(
            model_name='inscripcionprograma',
            name='sesiones_completadas',
            field=models.BooleanField(default=False, help_text='Indica si se han completado todas las sesiones'),
        ),
    ]
