# Generated by Django 5.1.7 on 2025-06-06 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0004_remove_programa_fecha_finalizacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscripcionprograma',
            old_name='estado_programa',
            new_name='estado_inscripcion',
        ),
    ]
