# Generated by Django 5.1.7 on 2025-06-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0005_rename_estado_programa_inscripcionprograma_estado_inscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcionprograma',
            name='estado_inscripcion',
            field=models.CharField(choices=[('en_progreso', 'En progreso'), ('completado', 'Completado'), ('abandonado', 'Abandonado')], default='en_progreso', max_length=20),
        ),
    ]
