# Generated by Django 5.1.7 on 2025-06-06 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0005_inscripcionprograma_cuestionarios_completados_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcionprograma',
            name='cuestionarios_completados',
        ),
        migrations.RemoveField(
            model_name='inscripcionprograma',
            name='diarios_completados',
        ),
        migrations.RemoveField(
            model_name='inscripcionprograma',
            name='sesiones_completadas',
        ),
    ]
