# Generated by Django 5.1.7 on 2025-05-05 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0005_alter_programa_creado_por'),
        ('usuario', '0007_remove_investigador_niveleducativo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='usuario.participante')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='programa.programa')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
                'unique_together': {('programa', 'participante')},
            },
        ),
    ]
