# Generated by Django 5.1.7 on 2025-05-11 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0006_programaparticipante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='escala',
        ),
    ]
