# Generated by Django 5.1.7 on 2025-05-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0007_remove_programa_escala'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programaparticipante',
            name='activo',
        ),
        migrations.AddField(
            model_name='programaparticipante',
            name='estado_programa',
            field=models.CharField(choices=[('en progreso', 'En progreso'), ('completado', 'Completado')], default='en progreso', max_length=20),
        ),
    ]
